### ISSUE TITLE
Twitter logs me out when using the extension

### ISSUE THREAD

**Issue by sebastiaanluca** [giuseppeg/refined-twitter-lite#10]
The extension was working fine, until 10 minutes ago. Twitter just redirects me to https://twitter.com/logout/error and shows the following screen. I can't do anything anymore when the plugin is enabled.

![Screenshot 2021-09-28 at 18 21 54](https://user-images.githubusercontent.com/711940/135126946-6338342d-373d-481b-ac7f-1999549df0f1.jpg)

macOS Big Sur
Chrome Version 94.0.4606.61 (Official Build) (arm64)
Refined Twitter Lite 0.3.18

**Comment by giuseppeg** [comment]
This is odd. Could you find more information in the devtools? Perhaps an error message or a stacktrace?

**Comment by sebastiaanluca** [comment]
Getting a lot of sourcemap warnings, but nothing out of the ordinary. No errors or so.

It's working fine again for now, the issue seems to happen from time to time. Maybe just a hiccup? I'll close the issue until I have more information for you to work with 😄

![Screenshot 2021-09-28 at 18 42 49](https://user-images.githubusercontent.com/711940/135129942-3a0d0c24-005d-417b-b566-1bf88e520bc1.jpg)
