### ISSUE TITLE
Post engagements are not being shown

### ISSUE THREAD

**Issue by hugobarauna** [giuseppeg/refined-twitter-lite#12]
When I access the post engagements page of one of my tweets, and I'm using the plunging, the list of likes, reposts, etc., is not being shown.

**Without the plugin**

![CleanShot 2023-09-27 at 10 24 27](https://github.com/giuseppeg/refined-twitter-lite/assets/2719/7f27ac94-29ac-432e-a999-527f1b8b4c36)

**With the plugin**

![CleanShot 2023-09-27 at 10 25 15](https://github.com/giuseppeg/refined-twitter-lite/assets/2719/59224e75-619e-4b3d-b966-de130426f4ba)

**Comment by giuseppeg** [comment]
Try to disable `hideTimelineSpam`, `tryToHideAds` or `hideExplore` with this command https://github.com/giuseppeg/refined-twitter-lite/blob/master/FEATURES.md#refined-twitter-lite

Unfortunately I didn't convert the extension to the new manifest and it was unpublished from the Chrome Web Store so I can't update it. Maybe I can republish it at some point but for now the solution above should do.

**Comment by hugobarauna** [comment]
`RefinedTwitterLite.setFeatures({hideTimelineSpam: false});` worked.

Thanks!  ☺️
